### ISSUE TITLE
Integration Software Entity

### ISSUE THREAD

**Issue by tmack8001** [bretterer/home-assistant-rivian#107]
Allow users of the integration to have a higher visibility to updates than HACS provides itself.

Having this entity would allow for users to setup push notifications, persistent web notifications or generally upon new releases have greater visibility to new releases when available.

```
type: entities
entities:
  - entity: update.home_assistant_core_update
  - entity: update.home_assistant_operating_system_update
  - entity: update.home_assistant_supervisor_update
  - entity: update.file_editor_update
  - entity: update.rivian_r1s_software
  - entity: update.rivian_r1t_software
  - entity: update.terminal_ssh_update
```

https://discord.com/channels/892997443896111105/997683089667018762/1119753701469458563
