### ISSUE TITLE
closure_state not correct

### ISSUE THREAD

**Issue by AlanJohnWilliams** [bretterer/home-assistant-rivian#156]
Hi! I just pulled together a few dashboard views of the Rivian integration data and started automating locking of my truck when at home. I'm noticing that closure_state doesn't always reflect closure status correctly. See track below for the last 6 hours where clearly doors have been opened but closure_state remains off. (I have also checked the raw entity results in HA to make sure it isn't an issue with my FLUX query or Grafana dashboard. 

<img width="1118" alt="image" src="https://github.com/bretterer/home-assistant-rivian/assets/35285037/bc5e69b9-6909-4438-b353-d97a855e00bd">

**Comment by tmack8001** [comment]
My child decided to trigger a long term test of my closure notification and auto locking feature on my trucks while out of town on a business trip.

My Rivian shows "open" and "closed" for this enclosure state fine (as pictured below).

Could you please provide a bit more context to your installation environment and entity that you are showing "off" and "on" statuses for.

![Screenshot_20240522-192957.png](https://github.com/bretterer/home-assistant-rivian/assets/2158627/3133c717-9e80-456f-8ea2-f9e790a62787)

**Comment by AlanJohnWilliams** [comment]
Hi @tmack8001 ,

The specific sensor is binary_sensor.sulley_closure_state created by the integration. If I look at binary_sensors for specific doors, they seem to change state as expected, eg binary_sensor.sulley_door_front_left, but binary_sensor.sulley_closure_state remains unchanged. 

Here is a view of the history panel showing that the front left door has been opened and closed, but sulley_closure_state stays closed/off:

<img width="1463" alt="image" src="https://github.com/bretterer/home-assistant-rivian/assets/35285037/67fcb46e-7aae-40c3-8a10-5ce61ee768c0">

In this time range, sulley_closure_state doesn't change at all, but over other periods I do see it changing, but not always when another opening changes. 

I've currently worked around this by creating a group for all the Rivian doors/windows that I want to monitor. this group works as expected (with perhaps the added benefit of not tracking the rear tailgate or tonneau cover.

```
group:
  sulley_secure_state:
    name: Sulley Secure Status of Doors and Opennings
    entities: 
      - binary_sensor.sulley_door_front_left
      - binary_sensor.sulley_door_front_right
      - binary_sensor.sulley_door_rear_left
      - binary_sensor.sulley_door_rear_right
      - binary_sensor.sulley_window_front_left
      - binary_sensor.sulley_window_front_right
      - binary_sensor.sulley_window_rear_left
      - binary_sensor.sulley_window_rear_right
      - binary_sensor.sulley_front_trunk
      - binary_sensor.sulley_gear_tunnel_right
      - binary_sensor.sulley_gear_tunnel_left
```
